server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ajanhari/config-repo.git
          default-label: main
          # Time limit to establish a connection with the remote repository
          timeout: 2
          # Clones the remote repository locally on startup
          clone-on-start: true
          # Forces pulling the remote repository and discarding any local changes
          force-pull: true

